<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17634" started-at="2017-09-25T06:51:44Z" finished-at="2017-09-25T06:52:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17634" started-at="2017-09-25T06:51:44Z" finished-at="2017-09-25T06:52:02Z">
      <class name="executionEngine.AboutEvent">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:executionEngine.AboutEvent@6d4b1c02]" name="beforeClass" is-config="true" duration-ms="4770" started-at="2017-09-25T12:21:44Z" finished-at="2017-09-25T12:21:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="AboutEventEdit()[pri:0, instance:executionEngine.AboutEvent@6d4b1c02]" name="AboutEventEdit" duration-ms="10518" started-at="2017-09-25T12:21:49Z" finished-at="2017-09-25T12:21:59Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utility.Utilis.ScrollDown(Utilis.java:28)
	at appModules.AboutEventEditAction.Editnews(AboutEventEditAction.java:24)
	at executionEngine.AboutEvent.AboutEventEdit(AboutEvent.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AboutEventEdit -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:executionEngine.AboutEvent@6d4b1c02]" name="afterClass" is-config="true" duration-ms="2319" started-at="2017-09-25T12:21:59Z" finished-at="2017-09-25T12:22:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- executionEngine.AboutEvent -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
